### ISSUE TITLE
执行报错

### ISSUE THREAD

**Issue by jjustwin** [yingoja/DemoAPI#1]
ft1.1: ******* 正在执行用例 ->event_login_001 *********
请求方式: post，请求URL: http://192.168.250.44:6223/xxx/sys/login
请求参数: 
post请求body类型为：json ,body内容为：{"t":1584687365417,"departmentNo":"440682111","username":"admin","password":"xxxxxx","uuid":"","captcha":""}
invalid syntax (<string>, line 1)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ddt.py", line 151, in wrapper
    return func(self, *args, **kwargs)
  File "E:\API_auto\DemoAPI\testcase\testAPI.py", line 35, in test_api
    self.result = re.json()
AttributeError: 'NoneType' object has no attribute 'json'

这个是report里报的错，看样子是请求失败了，但 不知道为何失败

这个接口postman，还有我单独使用r = requests.post(url, headers=h,data=data_body)都正常请求

另外，控制台的报错：
C:\ProgramData\Anaconda3\python.exe E:/API_auto/DemoAPI/run_demo.py
<_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'> 
Time Elapsed: 0:00:00.001006
E  test_api_1 (testAPI.Demo_API)
失败: server_hostname cannot be an empty string or start with a leading **dot.**

环境python3.7

**Comment by lijj0812** [comment]
#!/usr/bin/env python
# _*_ coding:utf-8 _*_
import configparser as cparser
from openpyxl.styles.colors import RED, GREEN, DARKYELLOW
from openpyxl.styles import Font, Alignment
from openpyxl import load_workbook
from config import setting
import shutil

import os
import sys
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

# --------- 读取config.ini配置文件 ---------------
cf = cparser.ConfigParser()
cf.read(setting.TEST_CONFIG, encoding='UTF-8')
name = cf.get("tester", "name")


class WriteExcel():
    """文件写入数据"""

    def __init__(self, fileName):
        self.filename = fileName
        if not os.path.exists(self.filename):
            # 文件不存在，则拷贝模板文件至指定报告目录下
            shutil.copyfile(setting.SOURCE_FILE, setting.TARGET_FILE)
        self.wb = load_workbook(self.filename)
        self.ws = self.wb.active

    def write_data(self, row_n, value):
        """
        写入测试结果
        :param row_n:数据所在行数
        :param value: 测试结果值
        :return: 无
        """
        font_GREEN = Font(name='宋体', color=GREEN, bold=True)
        font_RED = Font(name='宋体', color=RED, bold=True)
        font1 = Font(name='宋体', color=DARKYELLOW, bold=True)
        align = Alignment(horizontal='center', vertical='center')
        # 获数所在行数
        L_n = "L" + str(row_n)
        M_n = "M" + str(row_n)
        if value == "PASS":
            self.ws.cell(row_n, 12, value)
            self.ws[L_n].font = font_GREEN
        if value == "FAIL":
            self.ws.cell(row_n, 12, value)
            self.ws[L_n].font = font_RED
        self.ws.cell(row_n, 13, name)
        self.ws[L_n].alignment = align
        self.ws[M_n].font = font1
        self.ws[M_n].alignment = align
        self.wb.save(self.filename)
